import axios from '../src/lib/axios'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { useAuth } from '../src/hooks/auth'
import Link from 'next/link'


export default function Home() {
  const { user } = useAuth({ middleware: 'guest', redirectIfAuthenticated: '/dashboard', })

  useEffect(() => {
    axios('http://localhost:8000/api/test')
    .then((res) => console.log(res));
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='login'>Login</Link>
        <Link href='register'>Register</Link>
      </main>
    </div>
  )
}
