import axios from '../src/lib/axios'
import Head from 'next/head'
import { useEffect } from 'react'
import { useAuth } from '../src/hooks/auth'
import Link from 'next/link'


export default function Home() {
  const { user } = useAuth({ middleware: 'guest', redirectIfAuthenticated: '/dashboard', })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Link href='/'>Home</Link>
                <Link href='/login'>Login</Link>
                <Link href='/register'>Register</Link>
      </main>
    </div>
  )
}
