import Head from 'next/head'
import Link from 'next/link'
import { useAuth } from '../src/hooks/auth'
import { useState } from 'react'

const Register = () => {
    const { register } = useAuth({
        middleware: 'guest',
        redirectIfAuthenticated: '/dashboard',
    })

    const [name, setName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [passwordConfirmation, setPasswordConfirmation] = useState('')


    const submitForm = event => {
        event.preventDefault()

        register({
            name,
            email,
            password,
            password_confirmation: passwordConfirmation,
        })
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
            <Link href='/'>Home</Link>
                <Link href='/login'>Login</Link>
                <Link href='/register'>Register</Link>
                <form onSubmit={submitForm}>
                    <div>
                        <label>Name</label>
                        <input onChange={(e) => {setName(e.target.value)}} type="text" required/>
                    </div>
                    <div>
                        <label>Email</label>
                        <input onChange={(e) => {setEmail(e.target.value)}} type="email" required/>
                    </div>
                    <div>
                        <label>Password</label>
                        <input onChange={(e) => {setPassword(e.target.value)}} type="password" required/>
                    </div>
                    <div>
                        <label>Password Confirmation</label>
                        <input onChange={(e) => {setPasswordConfirmation(e.target.value)}} type="password" required/>
                    </div>
                    <div>
                        <button type="submit">Submit</button>
                    </div>
                </form>
            </main>
        </div>
    )
}

export default Register